### ISSUE TITLE
unable to control

### ISSUE THREAD

**Issue by nickfysiek** [akamming/Garmoticz#3]
added room with device, i can see it on my watch (forerunner 235) but i can not control the rooms.

**Comment by akamming** [comment]
can you be more specific? what is the switchtype you cannot control?

**Comment by nickfysiek** [comment]
i cans see the state of the switches but cannot put them on or off

________________________________
Van: akamming <notifications@github.com>
Verzonden: zondag 5 januari 2020 16:49
Aan: akamming/Garmoticz <Garmoticz@noreply.github.com>
CC: nickfysiek <lefeverenick@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [akamming/Garmoticz] unable to control (#3)


can you be more specific? what is the switchtype you cannot control?

**Comment by akamming** [comment]
Please reply directly in [github](https://github.com/akamming/Garmoticz/issues/3) of reply-ing to the email notifications, otherwise the entiremailthread is copied to github ;-)

As stated i need more info: What is the switchtype?

Can you give me the output of this URL (after logging into domoticz, otherwise it will not work) 
`http(s)://your_domoticz_url/json.htm?type=devices&rid=idx of the device you cannot switch
`
?

**Comment by akamming** [comment]
No response, so closing the issue
